"""Isolated CPython 3.14 semantic conformance cases for candidate runtimes.

Each case is a whole program executed in a fresh interpreter; its stdout and
success must equal CPython's. Cases only print; none use host capabilities.
Grouped by the requirement list in the migration brief. Adding a case never
changes a candidate's frozen-corpus score; it is separate evidence.
"""

CASES = {
    # -- comprehensions and iteration
    "listcomp_filter": "print([x * x for x in range(7) if x % 2 == 0])",
    "dictcomp": "print({x: x * 2 for x in range(7) if x > 3})",
    "setcomp": "print(sorted({x % 3 for x in range(7)}))",
    "nested_comp": "print([(a, b) for a in range(3) for b in range(a)])",
    "comp_of_comp": "print([[y for y in range(x)] for x in range(4)])",
    "genexpr_arg": "print(sum(x for x in range(7) if x > 2), sorted(x for x in 'cab'))",
    "genexpr_value": "g = (x for x in range(10**9))\nprint(next(g), next(g))",
    "any_all": "print(any(x > 5 for x in range(7)), all(x >= 0 for x in range(7)))",
    "map_filter": "print(list(map(lambda v: v + 1, [1, 2])), list(filter(None, [0, 1, '', 'a'])))",
    "zip_enumerate": "print(list(zip([1, 2, 3], 'ab')), list(enumerate('ab', start=1)))",
    "slices": "xs = list(range(7))\nprint(xs[::-2], xs[-2:], xs[1:-1:2], xs[10:], xs[-99:2])",
    "reversed_range": "print(list(reversed(range(1, 10, 3))), list(range(10, 0, -4)))",
    "for_else": "for i in range(2):\n    pass\nelse:\n    print('else', i)",
    "while_else_break": "n = 0\nwhile n < 5:\n    n += 1\n    if n == 3:\n        break\nelse:\n    print('never')\nprint(n)",
    "walrus": "data = [1, 5, 9]\nif (n := len(data)) > 2:\n    print(n)\nprint([y for x in data if (y := x * 2) > 5])",
    "unpacking": "a, (b, c), *rest = [1, (2, 3), 4, 5]\nfirst, *mid, last = 'abcde'\nprint(a, b, c, rest, first, mid, last)",
    "star_call": "def f(*a, **k):\n    return a, sorted(k.items())\nprint(f(*[1, 2], *(3,), **{'x': 1}, y=2))",
    "iter_protocol": "it = iter([1, 2])\nprint(next(it), next(it), next(it, 'end'))",
    # -- generators
    "generator_fn": "def gen(n):\n    for i in range(n):\n        yield i * i\ng = gen(4)\nprint(next(g), next(g), list(g))",
    "yield_from": "def a():\n    yield 1\n    yield 2\ndef b():\n    yield from a()\n    yield 3\nprint(list(b()))",
    "infinite_gen": "def c():\n    n = 0\n    while True:\n        n += 1\n        yield n\ng = c()\nprint([next(g) for _ in range(3)])",
    "gen_return_stop": "def g():\n    yield 1\n    return 5\nit = g()\nnext(it)\ntry:\n    next(it)\nexcept StopIteration as e:\n    print('stop', e.value)",
    # -- sorting
    "sorted_key_tuple": "rows = [{'id': 'b', 's': 2}, {'id': 'a', 's': 2}, {'id': 'c', 's': 5}]\nprint([r['id'] for r in sorted(rows, key=lambda r: (-r['s'], r['id']))])",
    "sorted_stable": "rows = [('b', 2), ('a', 2), ('c', 1)]\nprint(sorted(rows, key=lambda r: r[1]))",
    "sorted_reverse_stable": "rows = [('b', 2), ('a', 2), ('c', 5), ('d', 1)]\nprint(sorted(rows, key=lambda r: r[1], reverse=True))",
    "list_sort_inplace": "xs = ['b', 'A', 'a', 'B']\nxs.sort(key=str.lower)\nprint(xs, sorted(['b', 'A', 'a', 'B']))",
    "min_max_key_default": "print(min([3, 1], key=lambda v: -v), max([], default=None), max(1, 2.5), min('b', 'a'))",
    "sorted_dict_items": "d = {'z': 1, 'a': 2}\nprint(sorted(d), sorted(d.items(), key=lambda kv: kv[1]))",
    "sort_mixed_error": "try:\n    sorted([1, 'a'])\nexcept TypeError:\n    print('TypeError')",
    # -- dicts and sets
    "dict_order": "d = {'b': 1, 'a': 2}\nd['c'] = 3\nprint(list(d), list(d.values()), list(d.items()))",
    "dict_get": "d = {'a': 2}\nprint(d.get('a'), d.get('x'), d.get('x', 0), 'a' in d, 'x' not in d)",
    "dict_methods": "d = {'b': 1}\nprint(d.setdefault('e', []), d.pop('b'), d.pop('zz', 'none'), len(d))\nd.update({'f': 6}, g=7)\nprint(d)",
    "dict_counter": "c = {}\nfor w in 'a b a c b a'.split():\n    c[w] = c.get(w, 0) + 1\nprint(c)",
    "dict_del": "d = {'a': 1, 'b': 2}\ndel d['a']\nprint(d)",
    "dict_unpack_literal": "d = {'a': 1}\nprint({**d, 'z': 0}, dict(zip('ab', [1, 2])), dict([('k', 'v')]))",
    "dict_merge_op": "print({'a': 1} | {'b': 2})",
    "dict_keyerror": "try:\n    {}['missing']\nexcept KeyError as e:\n    print(repr(e), e.args)",
    "set_ops": "s = {3, 1, 2}\ns.add(4); s.discard(9); s.remove(1)\nprint(sorted(s), sorted(s | {9}), sorted(s & {2, 3}), sorted(s - {2}), sorted(s ^ {2, 7}))",
    "set_misc": "print(len(set('mississippi')), set() == set(), frozenset([1]) == {1}, {1, 2} <= {1, 2, 3})",
    "dict_view_ops": "d = {'a': 1, 'b': 2}\nprint(sorted(d.keys() & {'a', 'z'}), list(d.items())[0])",
    # -- Unicode strings
    "unicode_len_slice": "s = 'héllo wörld ✓ 😀'\nprint(len(s), s[:7], s[-3:], s[6:11])",
    "unicode_step_slice": "s = 'aé😀z'\nprint(s[::-1], s[::2])",
    "unicode_iter_ord": "print([c for c in 'a😀b'], len('😀'), ord('😀'), chr(128512))",
    "unicode_find": "s = 'héllo wörld ✓'\nprint(s.find('ö'), s.index('✓'), s.count('l'), s.upper())",
    "unicode_combining": "s = 'e\\u0301'\nprint(len(s), s[:1], repr(s[1:]))",
    "encode_bytes": "print('😀'.encode('utf-8'), len('😀é'.encode()), b'\\xc3\\xa9'.decode())",
    "case_mapping": "print('ÉCOLE'.lower(), 'straße'.upper(), 'ß'.casefold())",
    "str_split_family": "print('x\\ny\\r\\nz\\n'.splitlines(), 'a b  c'.split(), 'k=v=w'.partition('='), 'a.b.c'.rsplit('.', 1), 'a,b,,c'.split(','))",
    "str_predicates": "print('abc'.startswith('ab'), 'abc'.endswith(('x', 'c')), '42'.isdigit(), 'ab'.isalpha(), 'Ab c'.title(), 'a\\u00e9'.isascii())",
    "str_strip_family": "print(repr(' x\\t\\n'.rstrip()), 'xxhixx'.strip('x'), 'hello'.removeprefix('he'), 'hello'.removesuffix('lo'))",
    "str_pad": "print('7'.zfill(3), 'ab'.center(6, '*'), 'ab'.ljust(4, '.') + '|', '5'.rjust(3, '0'))",
    "str_replace_count": "t = 'aaa'\nprint(t.replace('a', 'b', 2), t.count('aa'), 'abc'.replace('', '-'))",
    "str_join_misc": "print(' | '.join(sorted({'b', 'a'})), 'x'.join([]), ''.join(reversed('abc')), 'ab' * 2)",
    "str_translate": "print('a-b_c'.translate(str.maketrans('-_', '  ')))",
    "name_escape": "print(len('\\N{GREEK SMALL LETTER ALPHA}'))",
    "str_repr_ascii": "print(repr('quote\\'\"\\n\\t\\x00é'), ascii('é'), str(b'x'))",
    "str_compare": "print('é' < 'z', 'Z' < 'a', 'abc' < 'abd', [1, 2] < [1, 3])",
    # -- formatting
    "format_spec": "print('{:>6}|{:<4}|{:^5}|{:08.3f}|{:,}'.format('ab', 'c', 'd', 3.14159, 1234567))",
    "fstring_spec": "s = 'hé'\nprint(f\"{s!r} {3/2:.2f} {10:x} {255:#06b} {'q'*3} {7:>3} {0.5:.0%}\")",
    "fstring_debug": "x = 3\nprint(f'{x=}', f'{x + 1 = }')",
    "percent_format": "print('%s-%d-%.1f' % ('a', 3, 2.25), '%05d' % 42, '%-5s|' % 'ab', '%x' % 255, '%(x)s' % {'x': 1})",
    "format_named": "print('{name}={value!r}'.format(name='k', value='v'), '{0}{1}{0}'.format('a', 'b'))",
    # -- numbers
    "int_division": "print(7 // 2, -7 // 2, 7 % 3, -7 % 3, divmod(-7, 2), 7 / 2, 2 ** -1)",
    "bigint": "print(2 ** 63, 2 ** 64 + 1, -(2 ** 63) - 1, 10 ** 20 // 3, 2 ** 100)",
    "int_precision": "print(9007199254740993 + 0, 9007199254740993 * 2, int('9007199254740993'))",
    "float_repr": "print(0.1 + 0.2, 1e16, 1.0, 1e-5, 3.0 * 1e21, float('1.5'), repr(0.1))",
    "int_parse": "print(int('42'), int(' -7 '), int(3.9), int(-3.9), int('ff', 16), int('1_000'))",
    "rounding": "print(round(2.5), round(3.5), round(2.675, 2), round(7), round(-0.5), f'{1234.5:.0f}', round(1.25, 1))",
    "fsum_builtin": "print(sum([0.1] * 10), sum(range(101)), sum([1, 2], 10))",
    "bool_int": "print(True + 1, True == 1, isinstance(True, int), 1 == 1.0, hash(1) == hash(1.0), {1: 'a', 1.0: 'b'})",
    "radix": "print(hex(255), bin(5), oct(8), abs(-3), abs(-2.5))",
    "aug_assign": "x = 5\nx += 3; x *= 2; x -= 1; x //= 3; x **= 2; x %= 7\nprint(x)",
    "chained_compare": "print(3 < 5 < 7, 1 < 2 > 3, 1 == 1.0 == True)",
    "inf_nan": "print(float('inf') > 10 ** 300, float('nan') != float('nan'), -0.0 == 0.0, str(-0.0))",
    "int_float_mix": "print(10 / 5, 2 * 0.5, 3 // 2.0, 7 % 2.5, 10 ** 16 * 1.0)",
    # -- JSON codec
    "json_int_precision": "import json\nv = json.loads('[9007199254740993, -9223372036854775808, 18446744073709551616]')\nprint(v, json.dumps(v))",
    "json_null_false_zero": "import json\nv = json.loads('{\"n\":null,\"f\":false,\"z\":0,\"e\":\"\",\"a\":[],\"o\":{}}')\nprint(v['n'] is None, v['f'] is False, v['z'] == 0 and v['z'] is not False, type(v['z']).__name__, v['a'] == [], v['o'] == {}, json.dumps(v))",
    "json_roundtrip_shapes": 'import json\nprint(json.dumps(json.loads(\'{"x":[[],[{}],{"y":[]}],"b":[true,false,null,0,0.0,""]}\')))',
    "json_default_dumps": "import json\nprint(json.dumps({'a': [1, True, None, 'hi', {}], 'b': {}, 'n': -9}))",
    "json_ensure_ascii": "import json\ns = 'é😀\\n\"\\\\/\\x01'\nprint(json.dumps(s), json.dumps(s, ensure_ascii=False))",
    "json_separators_sort": "import json\nprint(json.dumps({'b': 1, 'a': [1, 2]}, separators=(',', ':'), sort_keys=True))",
    "json_indent": "import json\nprint(json.dumps({'k': [1, 2], 'o': {'p': None}, 'e': [], 'd': {}}, indent=2))",
    "json_floats": "import json\nprint(json.dumps([1.0, 0.1, 1e16, 1e-5, 2.5e-7, -0.0, 123456789.125, 3.0e21, 1e100]))",
    "json_float_parse": "import json\nv = json.loads('[1.5, 1E2, -0, 1e-7, 0.30000000000000004]')\nprint(v, [type(x).__name__ for x in v])",
    "json_escapes_in": "import json\nprint(json.loads('\"\\\\u00e9\\\\ud83d\\\\ude00\\\\n\"'), len(json.loads('\"\\\\ud83d\\\\ude00\"')))",
    "json_scalars": "import json\nprint(json.loads('\"x\"'), json.loads('  3 '), json.dumps(True), json.dumps(None), json.dumps(''), json.dumps(0))",
    "json_invalid": "import json\nfor bad in ['{\"a\":1,}', '[1,]', \"{'a':1}\", '', '[1] x', '01', '{\"a\"}']:\n    try:\n        json.loads(bad)\n        print('accepted', repr(bad))\n    except ValueError as e:\n        print('rejected', repr(bad), type(e).__name__)",
    "json_decode_error_type": "import json\ntry:\n    json.loads('{')\nexcept json.JSONDecodeError as e:\n    print('JSONDecodeError', isinstance(e, ValueError))",
    "json_unserializable": "import json\ntry:\n    json.dumps({'s': {1, 2}})\nexcept TypeError:\n    print('TypeError')",
    "json_nonstr_keys": "import json\nprint(json.dumps({1: 'a', True: 'b', None: 'c', 2.5: 'd'}))",
    "json_tuple": "import json\nprint(json.dumps((1, (2, 3))), json.dumps({'k': (1,)}))",
    "json_nested_order": "import json\nprint(json.dumps({'d': {'b': 1, 'a': 2}, 'c': 3}))",
    "json_big_float_int": "import json\nprint(json.dumps(10 ** 30), json.loads('123456789012345678901234567890'), json.loads('1e400'))",
    "json_nan_dumps": "import json\ntry:\n    print(json.dumps(float('nan')))\n    print(json.dumps([float('inf')], allow_nan=False))\nexcept ValueError:\n    print('ValueError')",
    "json_duplicate_keys": 'import json\nprint(json.loads(\'{"a":1,"a":2}\'))',
    "json_deep": "import json\nprint(json.dumps(json.loads('[' * 50 + ']' * 50))[:8])",
    # -- exceptions
    "try_except_else_finally": "for n in range(2):\n    try:\n        if n:\n            raise ValueError('x')\n    except ValueError as e:\n        print('caught', e)\n    else:\n        print('else')\n    finally:\n        print('finally', n)",
    "exception_tuple": "try:\n    int('x')\nexcept (TypeError, ValueError) as e:\n    print(type(e).__name__, e)",
    "custom_exception": "class AppError(Exception):\n    def __init__(self, code):\n        super().__init__(f'code {code}')\n        self.code = code\ntry:\n    raise AppError(7)\nexcept AppError as e:\n    print(e.code, str(e), isinstance(e, Exception))",
    "raise_from": "try:\n    try:\n        1 / 0\n    except ZeroDivisionError as e:\n        raise RuntimeError('wrapped') from e\nexcept RuntimeError as e:\n    print(type(e).__name__, e, type(e.__cause__).__name__)",
    "builtin_errors": "for f in (lambda: [][1], lambda: None.foo, lambda: {}['k'], lambda: 1 / 0, lambda: int('x'), lambda: 'a' + 1):\n    try:\n        f()\n    except Exception as e:\n        print(type(e).__name__)",
    "name_error": "try:\n    undefined_name\nexcept NameError:\n    print('NameError')",
    "exception_hierarchy": "print(isinstance(KeyError('x'), LookupError), issubclass(ZeroDivisionError, ArithmeticError))",
    "reraise": "try:\n    try:\n        raise KeyError('k')\n    except KeyError:\n        raise\nexcept LookupError as e:\n    print('reraised', repr(e))",
    "uncaught_error_status": "raise ValueError('boom')",
    "assert_statement": "try:\n    assert 1 == 2, 'nope'\nexcept AssertionError as e:\n    print('assert', e)",
    "exception_str_args": "e = ValueError('a', 2)\nprint(str(e), e.args, repr(ValueError('m')))",
    # -- functions / classes / scope
    "closure_nonlocal": "def mk():\n    c = 0\n    def inc(step=1):\n        nonlocal c\n        c += step\n        return c\n    return inc\nf = mk()\nprint(f(), f(5))",
    "default_kwargs": "def f(a, b=2, *args, key=None, **kw):\n    return (a, b, args, key, sorted(kw.items()))\nprint(f(1), f(1, 3, 4, 5, key='k', z=1))",
    "recursion": "def fact(n):\n    return 1 if n <= 1 else n * fact(n - 1)\nprint(fact(25))",
    "global_stmt": "G = 1\ndef setg():\n    global G\n    G = 2\nsetg()\nprint(G)",
    "class_basic": "class P:\n    def __init__(self, x):\n        self.x = x\n    def __repr__(self):\n        return f'P({self.x})'\n    def double(self):\n        return self.x * 2\np = P(3)\nprint(p, p.double(), [p])",
    "class_inherit_super": "class A:\n    def __init__(self, x):\n        self.x = x\nclass B(A):\n    def __init__(self, x, y):\n        super().__init__(x)\n        self.y = y\nb = B(1, 2)\nprint(b.x, b.y, isinstance(b, A))",
    "class_dunder_lt": "class V:\n    def __init__(self, v):\n        self.v = v\n    def __lt__(self, o):\n        return self.v < o.v\nprint([x.v for x in sorted([V(3), V(1)])])",
    "dataclass_like": "class R:\n    __slots__ = ('a',)\n    def __init__(self, a):\n        self.a = a\nprint(R(1).a)",
    "lambda_default_capture": "fs = [lambda i=i: i for i in range(3)]\nprint([f() for f in fs])",
    "print_kwargs": "print('a', 'b', sep='-', end='!\\n')\nprint(print('x', end='') is None)",
    "type_checks": "print(isinstance([], (list, tuple)), type({}) is dict, type(None).__name__, callable(len), type(1.0).__name__)",
    "str_of_values": "print(str(None), str(True), [None, True, False], {'k': None}, (1,), ())",
    "del_statement": "x = [1, 2, 3]\ndel x[0]\ny = 1\ndel y\nprint(x)",
    "with_statement": "class C:\n    def __enter__(self):\n        print('enter')\n        return self\n    def __exit__(self, *a):\n        print('exit')\n        return False\nwith C():\n    print('body')",
    "match_statement": "v = {'kind': 'a', 'n': 2}\nmatch v:\n    case {'kind': 'a', 'n': n}:\n        print('a', n)\n    case _:\n        print('other')",
    "conditional_expr": "print('yes' if [] else 'no', 0 or 'default', 1 and 2, None or [])",
    "tuple_list_methods": "xs = [3, 1, 2]\nxs.append(4); xs.insert(0, 9); xs.extend([7]); xs.remove(1); p = xs.pop()\nprint(xs, p, xs.index(2), (1, 2, 1).count(1), xs.copy() == xs)",
    "string_to_list": "print(list('abc'), tuple([1, 2]), list({'a': 1}), list(range(3)))",
    "is_identity": "a = None\nb = []\nc = []\nprint(a is None, b is c, b is not None)",
    "getattr_default": "class O:\n    pass\no = O()\no.x = 1\nprint(getattr(o, 'x'), getattr(o, 'y', 'd'), hasattr(o, 'x'))",
}
