/* image_transform.c — optional ImageMagick 7 runner (ADR 0094).
 *
 * The only place in tny that starts an image converter, and only for an
 * explicitly requested export or contact sheet. See image_transform.h for the
 * argument-safety contract this file exists to enforce.
 */
#include "util/image_transform.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void fail(char *err, size_t errlen, const char *why) {
    if (err && errlen) snprintf(err, errlen, "%s", why);
}

/* Stage basenames are generated by tny, never by a caller's input: a short
 * lowercase ASCII component with no separator, no leading dot and no dash, so
 * it can never be read as an option or a coder prefix. */
static bool stage_name_ok(const char *name) {
    size_t n = name ? strlen(name) : 0;
    if (!n || n >= TNY_IMAGE_STAGE_NAME_MAX) return false;
    if (name[0] == '.' || name[0] == '-') return false;
    for (size_t i = 0; i < n; i++) {
        char c = name[i];
        bool ok = (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '.' || c == '_';
        if (!ok) return false;
    }
    return true;
}

char *tny_image_stage_path(const char *dir, const char *name) {
    if (!dir || *dir != '/' || !stage_name_ok(name)) return NULL;
    return path_join(dir, name);
}

#ifdef __EMSCRIPTEN__

/* wasm has no process seam (docs/adr/0017): there is no fourth platform
 * branch to add, and an export must fail before it opens an input, writes a
 * stage file or touches a destination. */
static const char UNSUPPORTED[] =
    "local image transforms need the optional ImageMagick 7 `magick` "
    "executable, which this build cannot run; generate and edit still work";

int tny_image_tool_resolve(tny_image_tool *out, bool (*cancelled)(void *), void *userdata,
                           char *err, size_t errlen) {
    (void)cancelled;
    (void)userdata;
    if (out) memset(out, 0, sizeof *out);
    fail(err, errlen, UNSUPPORTED);
    return 1;
}

int tny_image_tool_run(const tny_image_tool *tool, char *const argv[], const char *private_dir,
                       bool (*cancelled)(void *), void *userdata, buf_t *out, char *err,
                       size_t errlen) {
    (void)tool;
    (void)argv;
    (void)private_dir;
    (void)cancelled;
    (void)userdata;
    (void)out;
    fail(err, errlen, UNSUPPORTED);
    return 1;
}

char *tny_image_stage_dir(char *err, size_t errlen) {
    fail(err, errlen, UNSUPPORTED);
    return NULL;
}

void tny_image_stage_remove(const char *dir) { (void)dir; }

int tny_image_stage_write(const char *dir, const char *name, const void *data, size_t len,
                          char *err, size_t errlen) {
    (void)dir;
    (void)name;
    (void)data;
    (void)len;
    fail(err, errlen, UNSUPPORTED);
    return -1;
}

int tny_image_stage_read(const char *dir, const char *name, size_t max, buf_t *out, char *err,
                         size_t errlen) {
    (void)dir;
    (void)name;
    (void)max;
    (void)out;
    fail(err, errlen, UNSUPPORTED);
    return -1;
}

#else
#include "util/process.h"
#include "util/tny_poll.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>

extern char **environ;

/* A trusted literal root: never $TMPDIR, which a caller could point at a
 * shared or hostile directory. mkdtemp() creates the leaf 0700. */
#define STAGE_ROOT        "/tmp"
#define STAGE_TEMPLATE    "tny-image-export-XXXXXX"
/* A conversion cannot need more entries than tny wrote plus the tool's own
 * cache files; a directory larger than this is not silently swept. */
#define STAGE_ENTRIES_MAX 512

char *tny_image_stage_dir(char *err, size_t errlen) {
    char *dir = path_join(STAGE_ROOT, STAGE_TEMPLATE);
    if (!dir) {
        fail(err, errlen, "cannot create a private image staging directory");
        return NULL;
    }
    if (!mkdtemp(dir)) {
        free(dir);
        fail(err, errlen, "cannot create a private image staging directory");
        return NULL;
    }
    return dir;
}

void tny_image_stage_remove(const char *dir) {
    if (!dir || *dir != '/') return;
    DIR *d = opendir(dir);
    int fd = d ? dirfd(d) : -1;
    if (d) {
        struct dirent *entry;
        for (size_t i = 0; fd >= 0 && i < STAGE_ENTRIES_MAX && (entry = readdir(d)); i++) {
            if (strcmp(entry->d_name, ".") == 0 || strcmp(entry->d_name, "..") == 0) continue;
            /* The tool may leave its own bounded cache files here; remove them
             * relative to the directory itself, never through a rebuilt path
             * that a swapped component could redirect. */
            (void)unlinkat(fd, entry->d_name, 0);
        }
        closedir(d);
    }
    (void)rmdir(dir);
}

int tny_image_stage_write(const char *dir, const char *name, const void *data, size_t len,
                          char *err, size_t errlen) {
    char *path = tny_image_stage_path(dir, name);
    int fd = path ? open(path, O_WRONLY | O_CREAT | O_EXCL | O_NOFOLLOW | O_CLOEXEC, 0600) : -1;
    free(path);
    if (fd < 0) {
        fail(err, errlen, "cannot stage an image for conversion");
        return -1;
    }
    const char *p = data;
    size_t off = 0;
    int rc = 0;
    while (off < len) {
        ssize_t n = write(fd, p + off, len - off);
        if (n < 0 && errno == EINTR) continue;
        if (n <= 0) {
            rc = -1;
            break;
        }
        off += (size_t)n;
    }
    if (close(fd) != 0) rc = -1;
    if (rc) fail(err, errlen, "cannot stage an image for conversion");
    return rc;
}

int tny_image_stage_read(const char *dir, const char *name, size_t max, buf_t *out, char *err,
                         size_t errlen) {
    char *path = tny_image_stage_path(dir, name);
    int fd = path ? open(path, O_RDONLY | O_NOFOLLOW | O_CLOEXEC) : -1;
    free(path);
    struct stat st;
    int rc = -1;
    if (fd < 0) goto done;
    if (fstat(fd, &st) != 0 || !S_ISREG(st.st_mode) || st.st_size < 0 ||
        (uint64_t)st.st_size > (uint64_t)max)
        goto done;
    for (;;) {
        char chunk[8192];
        ssize_t n = read(fd, chunk, sizeof chunk);
        if (n < 0 && errno == EINTR) continue;
        if (n < 0 || (n > 0 && (size_t)n > max - out->len)) goto done;
        if (!n) break;
        buf_append(out, chunk, (size_t)n);
        if (out->oom) goto done;
    }
    rc = 0;
done:
    if (fd >= 0) close(fd);
    if (rc) {
        buf_free(out);
        buf_init(out);
        fail(err, errlen, "the image converter produced no readable output");
    }
    return rc;
}

/* ---- executable resolution ---------------------------------------------- */

static bool identity(const char *path, tny_image_tool *tool) {
    struct stat st;
    if (!path || stat(path, &st) != 0 || !S_ISREG(st.st_mode) ||
        !(st.st_mode & (S_IXUSR | S_IXGRP | S_IXOTH)))
        return false;
    tool->dev = (uint64_t)st.st_dev;
    tool->ino = (uint64_t)st.st_ino;
    tool->size = (int64_t)st.st_size;
    tool->mtime = (int64_t)st.st_mtime;
    return true;
}

/* The executable tny resolved must still be the executable tny is about to
 * start. A trusted dependency that was upgraded or replaced between two
 * invocations is reported, not assumed impossible. */
static bool identity_unchanged(const tny_image_tool *tool) {
    tny_image_tool now = {0};
    if (!identity(tool->path, &now)) return false;
    return now.dev == tool->dev && now.ino == tool->ino && now.size == tool->size &&
           now.mtime == tool->mtime;
}

/* First `magick` on PATH wins, exactly as a shell would resolve it, but the
 * result is pinned to one canonical absolute path with a known identity.
 * `convert` is never a fallback: it is ImageMagick 6's name and its option
 * semantics are not the ones this code validates against. */
static char *lookup_magick(void) {
    const char *path = getenv("PATH");
    if (!path || !*path) return NULL;
    const char *p = path;
    do {
        const char *end = strchr(p, ':');
        size_t n = end ? (size_t)(end - p) : strlen(p);
        /* An empty or relative PATH component means "the current directory" to
         * a shell; for an executable tny will run on the user's files, it is
         * refused rather than resolved. */
        char *dir = n && *p == '/' ? xstrndup(p, n) : NULL;
        char *candidate = dir ? path_join(dir, "magick") : NULL;
        free(dir);
        char *resolved = candidate ? path_abs(candidate) : NULL;
        free(candidate);
        if (resolved) {
            tny_image_tool probe = {0};
            if (identity(resolved, &probe)) return resolved;
            free(resolved);
        }
        p = end ? end + 1 : NULL;
    } while (p);
    return NULL;
}

/* "Version: ImageMagick 7.1.2-31 Q16 …" — read the major version and the
 * version token, and nothing else, out of bounded child stdout. */
static bool parse_version(const char *text, size_t len, tny_image_tool *tool) {
    static const char marker[] = "ImageMagick ";
    if (!text || len < sizeof marker) return false;
    const char *found = NULL;
    for (size_t i = 0; i + sizeof marker - 1 < len; i++)
        if (memcmp(text + i, marker, sizeof marker - 1) == 0) {
            found = text + i + sizeof marker - 1;
            break;
        }
    if (!found || *found < '1' || *found > '9') return false;
    size_t n = 0;
    while (found[n] && n + 1 < TNY_IMAGE_TOOL_VERSION_MAX && found[n] != ' ' && found[n] != '\n')
        n++;
    memcpy(tool->version, found, n);
    tool->version[n] = 0;
    tool->major = (unsigned)(*found - '0');
    return true;
}

int tny_image_tool_resolve(tny_image_tool *out, bool (*cancelled)(void *), void *userdata,
                           char *err, size_t errlen) {
    if (!out) return 1;
    memset(out, 0, sizeof *out);
    char *resolved = lookup_magick();
    if (!resolved || strlen(resolved) >= sizeof out->path) {
        free(resolved);
        fail(err, errlen,
             "local image exports need the optional ImageMagick 7 `magick` executable on PATH; "
             "image generation and editing do not");
        return 1;
    }
    snprintf(out->path, sizeof out->path, "%s", resolved);
    free(resolved);
    if (!identity(out->path, out)) {
        fail(err, errlen, "the resolved `magick` is not a regular executable file");
        return 1;
    }
    char *argv[] = {out->path, (char *)"-version", NULL};
    buf_t text;
    buf_init(&text);
    int rc = tny_image_tool_run(out, argv, NULL, cancelled, userdata, &text, err, errlen);
    bool parsed = !rc && parse_version(text.data, text.len, out);
    buf_free(&text);
    if (rc) return rc;
    if (!parsed) {
        fail(err, errlen, "the resolved `magick` did not report an ImageMagick version");
        return 1;
    }
    if (out->major != 7) {
        if (err && errlen)
            snprintf(err, errlen,
                     "local image exports need ImageMagick 7; the `magick` on PATH reports "
                     "version %s",
                     out->version);
        return 1;
    }
    return 0;
}

/* ---- one bounded child --------------------------------------------------- */

/* Exactly the variables a converter needs, built here rather than inherited:
 * no credentials, no MAGICK_* configuration or delegate overrides, and no
 * per-user ImageMagick config, because HOME points at the private stage.
 * The loader search paths are the one exception, because a relocatable
 * ImageMagick install cannot start without them. */
static char **child_env(const char *private_dir) {
    static const char *const inherited[] = {"LD_LIBRARY_PATH", "DYLD_LIBRARY_PATH",
                                            "DYLD_FALLBACK_LIBRARY_PATH"};
    size_t count = sizeof inherited / sizeof inherited[0];
    char **envp = calloc(count + 7, sizeof *envp);
    if (!envp) return NULL;
    size_t n = 0;
    buf_t entry;
    const char *home = private_dir && *private_dir == '/' ? private_dir : "/nonexistent";
    for (int i = 0; i < 2; i++) {
        buf_init(&entry);
        buf_appendf(&entry, "%s=%s", i ? "TMPDIR" : "HOME", home);
        envp[n] = entry.oom ? NULL : buf_detach(&entry);
        buf_free(&entry);
        if (!envp[n++]) goto oom;
    }
    static const char *const fixed[] = {"PATH=/usr/bin:/bin", "LANG=C", "LC_ALL=C",
                                        "MAGICK_THREAD_LIMIT=1"};
    for (size_t i = 0; i < sizeof fixed / sizeof fixed[0]; i++) {
        envp[n] = xstrdup(fixed[i]);
        if (!envp[n++]) goto oom;
    }
    for (size_t i = 0; i < count; i++) {
        const char *value = getenv(inherited[i]);
        if (!value || !*value) continue;
        buf_init(&entry);
        buf_appendf(&entry, "%s=%s", inherited[i], value);
        envp[n] = entry.oom ? NULL : buf_detach(&entry);
        buf_free(&entry);
        if (!envp[n++]) goto oom;
    }
    envp[n] = NULL;
    return envp;
oom:
    for (size_t i = 0; i < n; i++) free(envp[i]);
    free(envp);
    return NULL;
}

static void free_env(char **envp) {
    if (!envp) return;
    for (size_t i = 0; envp[i]; i++) free(envp[i]);
    free(envp);
}

/* The caller must still own this unreaped child. Keep its PID reserved until
 * all possible signaling finishes, then release ownership by reaping it. */
static void stop_child(pid_t pid) {
    (void)tny_process_kill_tree(pid);
    while (waitpid(pid, NULL, 0) < 0 && errno == EINTR) {}
}

int tny_image_tool_run(const tny_image_tool *tool, char *const argv[], const char *private_dir,
                       bool (*cancelled)(void *), void *userdata, buf_t *out, char *err,
                       size_t errlen) {
    if (!tool || !argv || !argv[0] || strcmp(argv[0], tool->path) != 0) {
        fail(err, errlen, "invalid image converter invocation");
        return 1;
    }
    if (!identity_unchanged(tool)) {
        fail(err, errlen, "the `magick` executable changed while this export was running");
        return 1;
    }
    if (cancelled && cancelled(userdata)) {
        fail(err, errlen, "the image export was interrupted");
        return 130;
    }
    int null_fd = open("/dev/null", O_RDONLY | O_CLOEXEC);
    int pipes[2] = {-1, -1};
    char **envp = child_env(private_dir);
    if (null_fd < 0 || !envp || pipe(pipes) != 0) {
        if (null_fd >= 0) close(null_fd);
        free_env(envp);
        fail(err, errlen, "cannot start the image converter");
        return 1;
    }
    /* Poll readiness is not a promise that a later read cannot block. */
    int flags = fcntl(pipes[0], F_GETFL);
    if (flags < 0 || fcntl(pipes[0], F_SETFL, flags | O_NONBLOCK) < 0) {
        close(null_fd);
        close(pipes[0]);
        close(pipes[1]);
        free_env(envp);
        fail(err, errlen, "cannot configure the image converter pipe");
        return 1;
    }
    pid_t pid = -1;
    int spawn_error = tny_process_spawn(argv, envp, null_fd, pipes[1], &pid);
    close(null_fd);
    close(pipes[1]);
    free_env(envp);
    if (spawn_error) {
        close(pipes[0]);
        fail(err, errlen, "cannot start the image converter");
        return 1;
    }
    int64_t deadline = monotonic_ms() + TNY_IMAGE_TOOL_WALL_MS;
    bool eof = false, overflow = false;
    int rc = 1, status = 0;

    for (;;) {
        /* One bounded nonblocking read per iteration, even after child exit.
         * Descendants can retain stdout; neither traffic nor exit bypasses
         * cancellation or the parent's wall deadline. */
        if (cancelled && cancelled(userdata)) {
            stop_child(pid);
            rc = 130;
            fail(err, errlen, "the image export was interrupted");
            goto done;
        }
        if (monotonic_ms() >= deadline) {
            stop_child(pid);
            fail(err, errlen, "the image converter exceeded its time limit and was stopped");
            goto done;
        }
        /* Do not reap while a descendant can still hold stdout. Cancellation
         * and deadline cleanup below need the direct child's reserved PID. */
        if (!eof) {
            struct pollfd pf = {pipes[0], POLLIN, 0};
            if (tny_poll(&pf, 1, 25) > 0) {
                char chunk[4096];
                ssize_t n = read(pipes[0], chunk, sizeof chunk);
                if (n > 0) {
                    if (out && !overflow && out->len + (size_t)n <= TNY_IMAGE_TOOL_STDOUT_MAX)
                        buf_append(out, chunk, (size_t)n);
                    else overflow = true;
                } else if (n == 0) eof = true;
                else if (errno != EINTR && errno != EAGAIN && errno != EWOULDBLOCK) {
                    stop_child(pid);
                    fail(err, errlen, "cannot read image converter output");
                    goto done;
                }
            }
        } else tny_poll(NULL, 0, 10);
        if (eof) {
            pid_t got = waitpid(pid, &status, WNOHANG);
            if (got == pid) {
                break; /* No signaling is permitted after ownership ends. */
            } else if (got < 0 && errno != EINTR) {
                /* Ownership is uncertain; never signal the numeric PID. */
                fail(err, errlen, "the image converter could not be waited for");
                goto done;
            }
        }
    }

    if (WIFEXITED(status) && WEXITSTATUS(status) == 0) rc = 0;
    else fail(err, errlen, "the image converter failed");
    if (!rc && cancelled && cancelled(userdata)) {
        rc = 130;
        fail(err, errlen, "the image export was interrupted");
    }
done:
    close(pipes[0]);
    if (out && (out->oom || overflow)) {
        buf_free(out);
        buf_init(out);
    }
    return rc;
}
#endif
