/* image_transform.h — the optional external image-transform tool (ADR 0094).
 *
 * This is a host OS seam like util/process.c and util/audio.c: the one place
 * allowed to know that an explicit export may run ImageMagick 7. tny links no
 * image decoder; `magick` is optional, is never required for provider
 * generation, and is only ever started by an explicitly requested export or
 * contact sheet.
 *
 * Nothing here knows about manifests, permissions or destinations. It resolves
 * one executable, owns a private staging directory, and runs bounded child
 * processes with a fixed argument vector and a sanitized environment. Callers
 * pass only their own generated ASCII stage paths and validated numeric or
 * enumerated tokens: a user pathname, a coder-looking string, an @file, a
 * bracket selector or a percent pattern must never reach these argv entries.
 *
 * wasm has no process seam at all, so every entry point here fails before it
 * opens, writes or removes anything.
 */
#ifndef TNY_IMAGE_TRANSFORM_H
#define TNY_IMAGE_TRANSFORM_H

#include "util/util.h"
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define TNY_IMAGE_TOOL_PATH_MAX    4096
#define TNY_IMAGE_TOOL_VERSION_MAX 64
/* Stage names are generated by tny and are always short fixed ASCII. */
#define TNY_IMAGE_STAGE_NAME_MAX 32
/* The parent's own wall-clock deadline for one child, beyond the tool's
 * documented `-limit time`. Neither is an OS sandbox (docs/adr/0094). */
#define TNY_IMAGE_TOOL_WALL_MS 75000
/* Diagnostics tny reads back from a child; product output is read from the
 * stage file, never from a pipe. */
#define TNY_IMAGE_TOOL_STDOUT_MAX (64u * 1024u)

/* A resolved executable plus the identity it had when it was resolved. The
 * same absolute path is used for the version probe, the producing conversion
 * and the verifying decode, and the identity is rechecked before each spawn:
 * a trusted dependency that is replaced mid-operation is detected, not
 * assumed impossible. */
typedef struct {
    char path[TNY_IMAGE_TOOL_PATH_MAX];
    char version[TNY_IMAGE_TOOL_VERSION_MAX]; /* e.g. "7.1.2-31" */
    uint64_t dev, ino;
    int64_t size, mtime;
    unsigned major;
} tny_image_tool;

/* Stable, machine-readable reasons an export could not run. */
#define TNY_IMAGE_TOOL_CODE_UNAVAILABLE "IMAGE_TOOL_UNAVAILABLE"
#define TNY_IMAGE_TOOL_CODE_CHANGED     "IMAGE_TOOL_CHANGED"
#define TNY_IMAGE_TOOL_CODE_FAILED      "IMAGE_TRANSFORM_FAILED"

/* Find ImageMagick 7 on the caller's PATH exactly once. Empty and relative
 * PATH components are skipped, each candidate is resolved with realpath() and
 * must be a regular executable, and `magick -version` must report major
 * version 7 — `convert` and ImageMagick 6 are never accepted, and tny's own
 * executable path is never consulted. 0 on success; 1 with a safe reason in
 * err, which never contains child output. */
int tny_image_tool_resolve(tny_image_tool *out, bool (*cancelled)(void *), void *userdata,
                           char *err, size_t errlen);

/* Run the resolved tool once. argv[0] must be tool->path and every later
 * entry must be a fixed token, a validated number or a tny-generated stage
 * path. The child gets a sanitized environment (no credentials, no MAGICK_*
 * configuration; HOME and TMPDIR are `private_dir` when one is given, so no
 * per-user ImageMagick configuration is read), its own process group, no
 * controlling stdin and a discarded stderr.
 *
 * The parent drains at most TNY_IMAGE_TOOL_STDOUT_MAX bytes of stdout into
 * `out` (may be NULL), checks `cancelled` and the wall deadline while waiting,
 * and on cancellation or timeout kills the whole child process group and reaps
 * it before returning. Returns 0 when the child exited 0, 130 when cancelled,
 * and 1 otherwise. */
int tny_image_tool_run(const tny_image_tool *tool, char *const argv[], const char *private_dir,
                       bool (*cancelled)(void *), void *userdata, buf_t *out, char *err,
                       size_t errlen);

/* Create a private 0700 staging directory with a generated name under a
 * trusted literal temporary root (never a caller-supplied path, never a
 * user-controlled TMPDIR). malloc'd absolute path; NULL fills err. */
char *tny_image_stage_dir(char *err, size_t errlen);
/* Remove every regular file the directory holds and then the directory. Safe
 * to call on NULL; a directory tny did not create is not removed, because the
 * name always comes from tny_image_stage_dir. */
void tny_image_stage_remove(const char *dir);
/* Write one stage file: a fixed ASCII basename, exclusive creation, 0600. */
int tny_image_stage_write(const char *dir, const char *name, const void *data, size_t len,
                          char *err, size_t errlen);
/* Read one stage file back, bounded. -1 leaves out empty and fills err. */
int tny_image_stage_read(const char *dir, const char *name, size_t max, buf_t *out, char *err,
                         size_t errlen);
/* Absolute path of one stage entry, for argv. malloc'd; NULL on exhaustion or
 * a name that is not a plain short ASCII component. */
char *tny_image_stage_path(const char *dir, const char *name);

#endif
