#!/usr/bin/env python3
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
schema = json.loads((ROOT / "sdk/schema/events.json").read_text())
events = schema["events"]
out = ROOT / "sdk/schema/generated"
out.mkdir(parents=True, exist_ok=True)

FIELD_TS = {
    "text": "text: string", "message_id": "messageId?: string",
    "tool_name": "toolName: string", "tool_id": "toolId: string",
    "tool_detail": "toolDetail: string", "tool_ok": "toolOk: boolean",
    "permission_id": "permissionId: string", "permission_summary": "permissionSummary: string",
    "permission_options": "permissionOptions: number", "input_tokens": "inputTokens: bigint",
    "output_tokens": "outputTokens: bigint", "context_used": "contextUsed: bigint",
    "context_size": "contextSize: bigint", "cost": "cost?: number", "has_cost": "hasCost: boolean",
    "stop_reason": "stopReason: TnyStopReason", "error_code": "errorCode: number",
    "message_type": "messageType?: string",
}
TS_HEADER = [
    "// Generated by sdk/schema/generate.py; do not edit.",
    f"export const EVENT_SCHEMA_VERSION = {schema['schema_version']} as const;",
    'export type TnyStopReason = "done" | "interrupted" | "denied" | "step_limit" | "error" | (string & {});',
    "export interface TnyEventEnvelope {",
    "  schemaVersion: number;", "  kind: number;", "  sequence: bigint;", "  timestampMs: bigint;",
    "  provider: string;", "  sessionId: string;", "  turnId: string;", "}",
    "export const eventKinds = {",
]
ts = TS_HEADER[:]
for e in events: ts.append(f"  {e['type']}: {e['id']},")
ts += ["} as const;", "", "export type TnyEventType = keyof typeof eventKinds;", ""]
for e in events:
    name=''.join(x.title() for x in e['type'].split('_'))+'Event'
    ts += [f"export interface {name} extends TnyEventEnvelope {{",
           f"  kind: typeof eventKinds.{e['type']};", f"  type: {e['type']!r};"]
    for f in e['fields']:
        if f in FIELD_TS: ts.append("  "+FIELD_TS[f]+";")
    ts += ["}", ""]
types=[''.join(x.title() for x in e['type'].split('_'))+'Event' for e in events]
ts += ["export interface UnknownEvent extends TnyEventEnvelope {",
       "  type: 'unknown';", "  originalType?: string;",
       "  payload: Readonly<Record<string, unknown>>;", "}", "",
       "export type KnownTnyEvent ="]
for i,n in enumerate(types): ts.append(f"  {'|' if i else ' '} {n}")
ts[-1] += ";"
ts += ["export type TnyEvent = KnownTnyEvent | UnknownEvent;", ""]
(out / "events.ts").write_text("\n".join(ts) + "\n")

py = ["# Generated by sdk/schema/generate.py; do not edit.", f"EVENT_SCHEMA_VERSION = {schema['schema_version']}", "EVENT_KINDS = {"]
for e in events: py.append(f"    {e['type']!r}: {e['id']},")
py += ["}", "EVENT_FIELDS = {"]
for e in events: py.append(f"    {e['type']!r}: {tuple(e['fields'])!r},")
py += ["}", ""]
(out / "events.py").write_text("\n".join(py))

fixture = {"schema_version": schema["schema_version"],
  "events": [{"id": e["id"], "type": e["type"], "fields": e["fields"]} for e in events],
  "unknown_event": {"id": 4294967295, "type": "future_event", "payload": {"future": True}}}
(ROOT / "sdk/schema/fixtures/events.json").write_text(json.dumps(fixture, indent=2) + "\n")
