/* Embedded CPython 3.14 for one host-authorized code cell (docs/adr/0180).
 *
 * The cell runs with the ordinary authority of the OS user: builtins, import,
 * open, subprocesses and sockets are CPython's own, and the standard library
 * is frozen into the executable (scripts/cpython_freeze_stdlib.py) with its
 * extension modules linked statically, so no host Python or stdlib directory
 * is consulted. Printed output and stderr go to the process's standard
 * descriptors, which the parent captures and bounds (code_runtime.c).
 *
 * What stays here are workflow bounds, not permission barriers: the metered
 * interpreter heap, the nested tool-call budget and the tools bridge. These
 * budgets are sticky: once a heap, call or callback limit trips, the cell is
 * terminal — every later tools use raises again, a pending call re-raises at
 * the next bytecode check, and the final result is the limit error whatever
 * the code caught. */
#define PY_SSIZE_T_CLEAN
#include <Python.h>

#include "core/code_python.h"
#include "core/code_policy.h"
#include "yyjson.h"
#include <stdatomic.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

/* Generated by scripts/cpython_freeze_stdlib.py into libtny_pystdlib.a. */
extern const struct _frozen tny_frozen_stdlib[];

/* Heap accounting ------------------------------------------------------- */

typedef union {
    max_align_t alignment;
    size_t size;
} allocation;

/* After the budget trips, unwinding (exception objects, tracebacks, frame
 * teardown) may still allocate from this reserve; nothing may use it to
 * continue work, because the cell is already terminal. */
#define HEAP_UNWIND_RESERVE (1024u * 1024u)

static struct {
    _Atomic unsigned long long used;
    _Atomic bool exhausted;
} heap;

static void budget_exhausted(void);

static bool heap_charge(size_t previous, size_t size) {
    unsigned long long used = atomic_load(&heap.used);
    for (;;) {
        unsigned long long base = used - previous;
        bool within = tny_code_memory_admit(base, size, sizeof(allocation), TNY_CODE_MEMORY_BYTES);
        if (!within) {
            if (!atomic_exchange(&heap.exhausted, true)) budget_exhausted();
            if (!tny_code_memory_admit(base, size, sizeof(allocation),
                                       TNY_CODE_MEMORY_BYTES + HEAP_UNWIND_RESERVE))
                return false;
        }
        unsigned long long next = base + sizeof(allocation) + size;
        if (atomic_compare_exchange_weak(&heap.used, &used, next)) return true;
    }
}

static void *heap_malloc(void *ctx, size_t size) {
    (void)ctx;
    if (!heap_charge(0, size)) return NULL;
    allocation *block = malloc(sizeof(*block) + size);
    if (!block) {
        atomic_fetch_sub(&heap.used, sizeof(*block) + size);
        return NULL;
    }
    block->size = size;
    return block + 1;
}

static void *heap_calloc(void *ctx, size_t count, size_t each) {
    if (each && count > SIZE_MAX / each) return NULL;
    void *p = heap_malloc(ctx, count * each);
    if (p) memset(p, 0, count * each);
    return p;
}

static void heap_free(void *ctx, void *ptr) {
    (void)ctx;
    if (!ptr) return;
    allocation *block = (allocation *)ptr - 1;
    atomic_fetch_sub(&heap.used, sizeof(*block) + block->size);
    free(block);
}

static void *heap_realloc(void *ctx, void *ptr, size_t size) {
    if (!ptr) return heap_malloc(ctx, size);
    allocation *block = (allocation *)ptr - 1;
    size_t previous = sizeof(*block) + block->size;
    if (!heap_charge(previous, size)) return NULL;
    allocation *next = realloc(block, sizeof(*next) + size);
    if (!next) {
        /* The old block remains valid and still charged at its old size. */
        atomic_fetch_add(&heap.used, previous);
        atomic_fetch_sub(&heap.used, sizeof(*next) + size);
        return NULL;
    }
    next->size = size;
    return next + 1;
}

static void *json_alloc(void *ctx, size_t size) { return heap_malloc(ctx, size); }
static void *json_realloc(void *ctx, void *ptr, size_t old, size_t size) {
    (void)old;
    return heap_realloc(ctx, ptr, size);
}
static void json_free(void *ctx, void *ptr) { heap_free(ctx, ptr); }
static const yyjson_alc heap_json = {json_alloc, json_realloc, json_free, NULL};

unsigned long long tny_code_python_heap_bytes(void) { return atomic_load(&heap.used); }

/* Cell state ------------------------------------------------------------ */

static struct {
    bool initialized;
    bool active;   /* code is executing */
    bool finished; /* code returned: no more tools, even from __del__ */
    pid_t pid;     /* the cell process; a fork() child has no tool authority */
    const tny_code_python_host *host;
    const char *fatal; /* sticky terminal limit, static text */
    unsigned calls;
    PyObject *limit_error; /* BaseException subclass: not caught by `except Exception` */
} cell;

static int fatal_pending(void *arg) {
    (void)arg;
    if (!cell.active || !cell.fatal) return 0;
    PyErr_SetString(cell.limit_error, cell.fatal);
    (void)Py_AddPendingCall(fatal_pending, NULL);
    return -1;
}

/* Mark the cell terminal and raise; returns NULL for the caller to return. */
static PyObject *terminal(const char *reason) {
    if (!cell.fatal) {
        cell.fatal = reason;
        if (cell.host && cell.host->abort) cell.host->abort(cell.host->userdata, cell.fatal);
        (void)Py_AddPendingCall(fatal_pending, NULL);
    }
    if (!PyErr_Occurred()) PyErr_SetString(cell.limit_error, cell.fatal);
    return NULL;
}

static void budget_exhausted(void) {
    if (!cell.fatal) {
        cell.fatal = "memory limit exceeded";
        if (cell.host && cell.host->abort) cell.host->abort(cell.host->userdata, cell.fatal);
    }
    /* Hosts without a terminal handler retain bounded exception unwinding. */
    if (cell.active) (void)Py_AddPendingCall(fatal_pending, NULL);
}

static bool refuse_after_limit(void) {
    if (cell.fatal) {
        PyErr_SetString(cell.limit_error, cell.fatal);
        return true;
    }
    if (cell.finished || !cell.active) {
        PyErr_SetString(PyExc_RuntimeError, "the code cell has finished; tools are closed");
        return true;
    }
    if (getpid() != cell.pid) {
        /* Only the cell process talks to the parent; see code_runtime.c. */
        PyErr_SetString(PyExc_RuntimeError, "tools are unavailable in a forked child process");
        return true;
    }
    return false;
}

/* tools ------------------------------------------------------------------ */

static bool json_object_text(const char *text, size_t len) {
    yyjson_doc *doc = yyjson_read_opts((char *)text, len, 0, &heap_json, NULL);
    bool object = doc && yyjson_is_obj(yyjson_doc_get_root(doc));
    yyjson_doc_free(doc);
    return object;
}

static PyObject *tools_call(PyObject *self, PyObject *const *args, Py_ssize_t nargs) {
    (void)self;
    if (nargs != 2 || !PyUnicode_Check(args[0]) || !PyUnicode_Check(args[1])) {
        PyErr_SetString(PyExc_TypeError,
                        "tools.call(name, arguments_json) takes two strings: a tool name and "
                        "JSON object text such as json.dumps({...})");
        return NULL;
    }
    if (refuse_after_limit()) return NULL;
    Py_ssize_t name_len = 0, args_len = 0;
    const char *name = PyUnicode_AsUTF8AndSize(args[0], &name_len);
    const char *arguments = name ? PyUnicode_AsUTF8AndSize(args[1], &args_len) : NULL;
    if (!arguments) return NULL;
    if (memchr(name, 0, (size_t)name_len) || memchr(arguments, 0, (size_t)args_len)) {
        PyErr_SetString(PyExc_ValueError, "tool name and arguments cannot contain NUL");
        return NULL;
    }
    bool recursive = strcmp(name, "run_code") == 0;
    if (!name_len || name_len > TNY_CODE_NAME_BYTES) {
        PyErr_SetString(PyExc_ValueError, "invalid tool name");
        return NULL;
    }
    if (recursive) {
        PyErr_SetString(PyExc_ValueError, "recursive run_code is forbidden");
        return NULL;
    }
    if ((size_t)args_len > TNY_CODE_ARGUMENT_BYTES) {
        PyErr_SetString(PyExc_ValueError, "tool arguments limit exceeded");
        return NULL;
    }
    bool object = json_object_text(arguments, (size_t)args_len);
    if (cell.fatal) return terminal(cell.fatal);
    if (!object) {
        PyErr_SetString(PyExc_ValueError, "tool arguments must be JSON object text");
        return NULL;
    }
    if (!tny_code_call_admit(cell.calls, (uint64_t)name_len, recursive, (uint64_t)args_len, object))
        return terminal("tool call limit exceeded");
    ++cell.calls;
    const tny_code_python_host *host = cell.host;
    char *result = host && host->call ? host->call(host->userdata, name, arguments) : NULL;
    if (!result) {
        const char *reason = host && host->failure ? host->failure(host->userdata) : NULL;
        return terminal(reason ? reason : "tool callback failed");
    }
    size_t len = strlen(result);
    if (!tny_code_result_admit(len)) {
        free(result);
        return terminal("tool result limit exceeded");
    }
    PyObject *text = PyUnicode_DecodeUTF8(result, (Py_ssize_t)len, "replace");
    free(result);
    return text;
}

static PyObject *tools_list(PyObject *self, PyObject *unused) {
    (void)self;
    (void)unused;
    if (refuse_after_limit()) return NULL;
    return PyUnicode_FromString(cell.host && cell.host->catalog ? cell.host->catalog : "[]");
}

static PyObject *tools_describe(PyObject *self, PyObject *name_obj) {
    (void)self;
    if (!PyUnicode_Check(name_obj)) {
        PyErr_SetString(PyExc_TypeError, "tools.describe(name) takes a tool name string");
        return NULL;
    }
    if (refuse_after_limit()) return NULL;
    Py_ssize_t name_len = 0;
    const char *name = PyUnicode_AsUTF8AndSize(name_obj, &name_len);
    if (!name) return NULL;
    if (memchr(name, 0, (size_t)name_len)) {
        PyErr_SetString(PyExc_ValueError, "tool name cannot contain NUL");
        return NULL;
    }
    const char *catalog = cell.host && cell.host->catalog ? cell.host->catalog : "[]";
    yyjson_doc *doc = yyjson_read_opts((char *)catalog, strlen(catalog), 0, &heap_json, NULL);
    if (!doc) return cell.fatal ? terminal(cell.fatal) : PyErr_NoMemory();
    yyjson_val *entry;
    size_t index, count;
    PyObject *found = NULL;
    yyjson_arr_foreach(yyjson_doc_get_root(doc), index, count, entry) {
        yyjson_val *fn = yyjson_obj_get(entry, "function");
        const char *candidate = yyjson_get_str(yyjson_obj_get(fn ? fn : entry, "name"));
        if (!candidate || strcmp(candidate, name) != 0) continue;
        size_t len = 0;
        char *text = yyjson_val_write_opts(entry, 0, &heap_json, &len, NULL);
        if (text) {
            found = PyUnicode_DecodeUTF8(text, (Py_ssize_t)len, "strict");
            json_free(NULL, text);
        } else if (cell.fatal) terminal(cell.fatal);
        else PyErr_NoMemory();
        break;
    }
    yyjson_doc_free(doc);
    if (found || PyErr_Occurred()) return found;
    Py_RETURN_NONE;
}

static PyMethodDef tools_methods[] = {
    {"call", (PyCFunction)(void (*)(void))tools_call, METH_FASTCALL,
     "call(name, arguments_json) -> str: run a permitted nested tool"},
    {"list", tools_list, METH_NOARGS, "list() -> str: JSON catalog of permitted tools"},
    {"describe", tools_describe, METH_O, "describe(name) -> str | None: one tool's JSON schema"},
    {NULL, NULL, 0, NULL},
};

/* Lifecycle -------------------------------------------------------------- */

bool tny_code_python_available(void) { return true; }

/* The static OpenSSL looks for CA certificates under OPENSSLDIR=/etc/ssl.
 * Hosts without /etc/ssl/cert.pem keep their bundle elsewhere; point
 * SSL_CERT_FILE at the first common location, exactly as a user would, unless
 * the environment already chose a file or directory. Child processes inherit
 * the variable. */
static void default_trust_store(void) {
    static const char *const bundles[] = {
        "/etc/ssl/certs/ca-certificates.crt",                /* Debian, Arch, NixOS, Gentoo */
        "/etc/pki/tls/certs/ca-bundle.crt",                  /* Fedora, RHEL */
        "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem", /* RHEL 7+ */
        "/etc/ssl/ca-bundle.pem",                            /* openSUSE */
        "/etc/pki/tls/cacert.pem",                           /* OpenELEC */
        NULL,
    };
    if (getenv("SSL_CERT_FILE") || getenv("SSL_CERT_DIR") || access("/etc/ssl/cert.pem", R_OK) == 0)
        return;
    for (size_t i = 0; bundles[i]; ++i)
        if (access(bundles[i], R_OK) == 0) {
            (void)setenv("SSL_CERT_FILE", bundles[i], 0);
            return;
        }
}

int tny_code_python_init(void) {
    if (cell.initialized) return 0;
    PyMemAllocatorEx allocator = {NULL, heap_malloc, heap_calloc, heap_realloc, heap_free};
    PyMem_SetAllocator(PYMEM_DOMAIN_RAW, &allocator);
    PyMem_SetAllocator(PYMEM_DOMAIN_MEM, &allocator);
    PyMem_SetAllocator(PYMEM_DOMAIN_OBJ, &allocator);
    PyImport_FrozenModules = tny_frozen_stdlib;
    default_trust_store();
    PyPreConfig pre;
    PyPreConfig_InitIsolatedConfig(&pre);
    pre.utf8_mode = 1;
    PyStatus status = Py_PreInitialize(&pre);
    if (PyStatus_Exception(status)) return -1;
    /* Isolated from PYTHON* variables and user site-packages: the embedded
     * runtime never adopts a host installation's paths. The process
     * environment itself is the host's and reaches os.environ unchanged. */
    PyConfig config;
    PyConfig_InitIsolatedConfig(&config);
    config.site_import = 0;
    config.write_bytecode = 0;
    /* Python's normal signal setup: SIGPIPE ignored (BrokenPipeError instead
     * of death), SIGINT raises KeyboardInterrupt; subprocess restores them. */
    config.install_signal_handlers = 1;
    config.configure_c_stdio = 0;
    config.pathconfig_warnings = 0;
    config.use_frozen_modules = 1;
    config.faulthandler = 0;
    config.tracemalloc = 0;
    /* Unbuffered stdio keeps print() ordered with subprocess output. */
    config.buffered_stdio = 0;
    /* sys.path is [""] as for `python -c`: the working directory's own
     * modules import; the frozen stdlib is found first and cannot be
     * shadowed. There is no Python executable to re-launch, so
     * sys.executable is empty (multiprocessing needs the "fork" context). */
    config.module_search_paths_set = 1;
    status = PyWideStringList_Append(&config.module_search_paths, L"");
    /* A program name that is never on PATH keeps path discovery from
     * adopting a host python3 as sys.executable. */
    if (!PyStatus_Exception(status))
        status = PyConfig_SetString(&config, &config.program_name, L"tny-code-cell");
    if (!PyStatus_Exception(status))
        status = PyConfig_SetString(&config, &config.home, L"/nonexistent-tny-python-home");
    if (!PyStatus_Exception(status)) status = Py_InitializeFromConfig(&config);
    PyConfig_Clear(&config);
    if (PyStatus_Exception(status)) return -1;
    PyObject *empty = PyUnicode_FromString("");
    bool executable = empty && PySys_SetObject("executable", empty) == 0 &&
                      PySys_SetObject("_base_executable", empty) == 0;
    Py_XDECREF(empty);
    if (!executable) {
        PyErr_Clear();
        return -1;
    }
    cell.limit_error = PyErr_NewExceptionWithDoc(
        "tny.CellLimitError", "A code-cell budget was exhausted; the cell is terminal.",
        PyExc_BaseException, NULL);
    if (!cell.limit_error) {
        PyErr_Clear();
        return -1;
    }
    cell.initialized = true;
    return 0;
}

/* A fresh __main__ with the tools bridge and json pre-bound, as the prompt
 * promises; `import tools` also works. Everything else is ordinary CPython. */
static PyObject *cell_globals(void) {
    PyObject *modules = PyImport_GetModuleDict();
    if (PyDict_PopString(modules, "__main__", NULL) < 0) return NULL;
    PyObject *main = PyImport_AddModuleRef("__main__");
    PyObject *globals = main ? PyModule_GetDict(main) : NULL;
    PyObject *builtins = globals ? PyImport_ImportModule("builtins") : NULL;
    PyObject *tools = builtins ? PyModule_New("tools") : NULL;
    PyObject *json = tools ? PyImport_ImportModule("json") : NULL;
    bool ok = json && PyDict_SetItemString(globals, "__builtins__", builtins) == 0 &&
              PyModule_AddFunctions(tools, tools_methods) == 0 &&
              PyModule_AddObjectRef(tools, "CellLimitError", cell.limit_error) == 0 &&
              PyDict_SetItemString(modules, "tools", tools) == 0 &&
              PyDict_SetItemString(globals, "tools", tools) == 0 &&
              PyDict_SetItemString(globals, "json", json) == 0;
    Py_XINCREF(globals);
    Py_XDECREF(main);
    Py_XDECREF(builtins);
    Py_XDECREF(tools);
    Py_XDECREF(json);
    if (!ok) Py_CLEAR(globals);
    return globals;
}

static char *copy_text(const char *text) {
    char *copy = malloc(strlen(text) + 1);
    return copy ? strcpy(copy, text) : NULL;
}

/* "error: code: Type: message (line N)" for the last frame in the cell. */
static char *format_exception(PyObject *error) {
    PyObject *text = PyObject_Str(error);
    const char *message = text ? PyUnicode_AsUTF8(text) : NULL;
    if (!message) PyErr_Clear();
    const char *type = Py_TYPE(error)->tp_name;
    const char *dot = strrchr(type, '.');
    type = dot ? dot + 1 : type;
    long line = -1;
    if (PyErr_GivenExceptionMatches(error, PyExc_SyntaxError)) {
        PyObject *lineno = PyObject_GetAttrString(error, "lineno");
        line = lineno && PyLong_Check(lineno) ? PyLong_AsLong(lineno) : -1;
        Py_XDECREF(lineno);
        PyErr_Clear();
    }
    PyObject *tb = PyException_GetTraceback(error);
    for (PyObject *t = tb; t && t != Py_None;) {
        PyObject *lineno = PyObject_GetAttrString(t, "tb_lineno");
        PyObject *frame = PyObject_GetAttrString(t, "tb_frame");
        PyCodeObject *code = frame ? PyFrame_GetCode((PyFrameObject *)frame) : NULL;
        const char *file = code ? PyUnicode_AsUTF8(code->co_filename) : NULL;
        if (file && strcmp(file, "<code>") == 0 && lineno) line = PyLong_AsLong(lineno);
        Py_XDECREF((PyObject *)code);
        Py_XDECREF(frame);
        Py_XDECREF(lineno);
        PyObject *next = PyObject_GetAttrString(t, "tb_next");
        if (t != tb) Py_DECREF(t);
        t = next;
        if (!t) break;
    }
    Py_XDECREF(tb);
    PyErr_Clear();
    size_t cap = TNY_CODE_OUTPUT_BYTES / 2 + 256;
    char *out = malloc(cap);
    if (!out) {
        Py_XDECREF(text);
        return NULL;
    }
    int n = snprintf(out, cap, "error: code: %s%s%.*s", type, message && *message ? ": " : "",
                     (int)(TNY_CODE_OUTPUT_BYTES / 2), message ? message : "");
    if (line > 0 && n > 0 && (size_t)n < cap)
        snprintf(out + n, cap - (size_t)n, " (line %ld)", line);
    Py_XDECREF(text);
    return out;
}

/* The full traceback goes to stderr like `python -c`, with the cell's own
 * source lines, uncolored. Best effort: a failure here keeps the summary. */
static void print_traceback(PyObject *error, const char *code) {
    PyObject *linecache = PyImport_ImportModule("linecache");
    PyObject *cache = linecache ? PyObject_GetAttrString(linecache, "cache") : NULL;
    PyObject *source = cache ? PyUnicode_FromString(code) : NULL;
    PyObject *lines = source ? PyUnicode_Splitlines(source, 1) : NULL;
    PyObject *entry =
        lines ? Py_BuildValue("(nOOs)", PyUnicode_GET_LENGTH(source), Py_None, lines, "<code>")
              : NULL;
    if (entry && PyDict_Check(cache)) (void)PyDict_SetItemString(cache, "<code>", entry);
    PyErr_Clear();
    PyObject *traceback = PyImport_ImportModule("traceback");
    PyObject *printed =
        traceback ? PyObject_CallMethod(traceback, "print_exception", "O", error) : NULL;
    Py_XDECREF(printed);
    Py_XDECREF(traceback);
    Py_XDECREF(entry);
    Py_XDECREF(lines);
    Py_XDECREF(source);
    Py_XDECREF(cache);
    Py_XDECREF(linecache);
    PyErr_Clear();
}

/* SystemExit ends the cell like the interpreter: None/0 succeed, any other
 * code is an error that names it. Returns NULL for success. */
static char *system_exit(PyObject *error) {
    PyObject *code = PyObject_GetAttrString(error, "code");
    PyErr_Clear();
    bool success = !code || code == Py_None ||
                   (PyLong_Check(code) && PyLong_AsLong(code) == 0 && !PyErr_Occurred());
    PyErr_Clear();
    char *out = NULL;
    if (!success) {
        PyObject *text = PyObject_Str(code);
        const char *value = text ? PyUnicode_AsUTF8(text) : NULL;
        PyErr_Clear();
        size_t cap = 64 + TNY_CODE_OUTPUT_BYTES / 2;
        out = malloc(cap);
        if (out)
            snprintf(out, cap, "error: code: SystemExit: %.*s", (int)(TNY_CODE_OUTPUT_BYTES / 2),
                     value ? value : "?");
        Py_XDECREF(text);
    }
    Py_XDECREF(code);
    return out || success ? out : copy_text("error: code: SystemExit");
}

/* As at interpreter exit, while the cell is still live: non-daemon threads
 * finish, atexit handlers (including weakref.finalize cleanups such as
 * tempfile's) run, and Python-level stdio buffers are flushed. */
static void settle_process_state(void) {
    static const char *const steps[][2] = {{"threading", "_shutdown"},
                                           {"atexit", "_run_exitfuncs"}};
    PyObject *modules = PyImport_GetModuleDict();
    for (size_t i = 0; i < sizeof steps / sizeof *steps; ++i) {
        PyObject *module = modules ? PyDict_GetItemString(modules, steps[i][0]) : NULL;
        PyObject *done = module ? PyObject_CallMethod(module, steps[i][1], NULL) : NULL;
        Py_XDECREF(done);
        PyErr_Clear();
    }
    static const char *const streams[] = {"stdout", "stderr"};
    for (size_t i = 0; i < 2; ++i) {
        PyObject *stream = PySys_GetObject(streams[i]);
        PyObject *done =
            stream && stream != Py_None ? PyObject_CallMethod(stream, "flush", NULL) : NULL;
        Py_XDECREF(done);
        PyErr_Clear();
    }
}

char *tny_code_python_run(const char *code, const tny_code_python_host *host) {
    if (!code || !tny_code_source_admit(strlen(code)))
        return copy_text("error: code: source limit exceeded");
    if (!cell.initialized && tny_code_python_init() != 0)
        return copy_text("error: code: Python runtime initialization failed");
    cell.host = host;
    cell.fatal = NULL;
    cell.calls = 0;
    cell.finished = false;
    cell.pid = getpid();
    atomic_store(&heap.exhausted, false);
    PyObject *globals = cell_globals();
    PyObject *compiled = globals && !cell.fatal
                             ? Py_CompileStringExFlags(code, "<code>", Py_file_input, NULL, -1)
                             : NULL;
    /* A budget that tripped during setup or compilation is terminal even if the
     * unwind reserve let a code object through: never run it. */
    cell.active = compiled && !cell.fatal;
    PyObject *result = cell.active ? PyEval_EvalCode(compiled, globals, globals) : NULL;
    char *text = NULL;
    bool failed = !result && !cell.fatal;
    if (cell.fatal) PyErr_Clear();
    else if (failed) {
        PyObject *error = PyErr_GetRaisedException();
        if (error && PyErr_GivenExceptionMatches(error, PyExc_SystemExit)) {
            text = system_exit(error);
            failed = text != NULL;
        } else if (error) {
            text = format_exception(error);
            print_traceback(error, code);
        } else text = copy_text("error: code: unknown failure");
        Py_XDECREF(error);
    }
    if (!cell.fatal) settle_process_state();
    cell.active = false;
    cell.finished = true;
    Py_XDECREF(result);
    Py_XDECREF(compiled);
    /* The cell process exits right after its result, without finalizers;
     * an in-process host's next run replaces __main__ with tools closed. */
    Py_XDECREF(globals);
    PyErr_Clear();
    /* A limit decides the result wherever it tripped, including in an
     * exception's __str__ or a finalizer after the code returned. */
    if (cell.fatal) {
        free(text);
        size_t cap = 64 + strlen(cell.fatal);
        text = malloc(cap);
        if (text) snprintf(text, cap, "error: code: %s", cell.fatal);
    } else if (!failed) {
        free(text);
        text = copy_text("");
    }
    cell.host = NULL;
    return text;
}

void tny_code_python_fini(void) {
    if (!cell.initialized) return;
    Py_CLEAR(cell.limit_error);
    (void)Py_FinalizeEx();
    cell.initialized = false;
}
